# Generated by Django 4.0.6 on 2022-09-23 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=120)),
                ('author_name', models.CharField(max_length=120)),
                ('price', models.FloatField(null=True)),
                ('publisher', models.CharField(max_length=120)),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
